---
title: R语言学习资源总结
author: ''
date: '2019-08-17'
categories:
  - R
tags:
  - 教程
slug: r-resources-collection
output:
  blogdown::html_page:
    toc: yes
---

# Communication

 - [Starting a Rmarkdown Blog with Blogdown + Hugo + Github](https://talesofr.wordpress.com/2017/08/18/starting-a-rmarkdown-blog-with-bookdown-hugo-github/) (181110)  
 看了好几篇介绍用`blogdown`搭建博客的文章，只有这一篇文章介绍的方法让我成功了。
 
  - [Adding GIF animations](https://blogdown-demo.rbind.io/2018/01/31/gif-animations/) (190228; 190311)  
 介绍了在`blogdown`中添加动图和生成动图的方法。

 - [Create Multiple Reports with RMarkdown](https://www.reed.edu/data-at-reed/software/R/markdown_multiple_reports.html) (181129; 190311)  
 使用`Rmarkdown`批量生成报告的教程，测试有效，非常实用。
 
 - [MANY REPORTS FROM 1 RMARKDOWN FILE](https://scottishsnow.wordpress.com/2018/08/17/many-reports-from-1-rmarkdown-file/) (190311)  
 另一篇使用`Rmarkdown`批量生成报告的教程，没有实际测试，但应该没问题。

 - [Happy collaboration with Rmd to docx](https://rmarkdown.rstudio.com/articles_docx.html) (181110)  
 因为工作中要写的报告基本上都是word文档，而写报告其实主要是在已有框架的基础上修改大量的短语和数字，很让人烦躁，于是就研究了下如何生成（至少半）自动化的word文档。


# Concept & History
 
 - [Explain R environments like I’m five](https://colinfay.me/explain-environments-eli5/?utm_campaign=News&utm_medium=Community&utm_source=DataCamp.com) (181110; 190307)  
 介绍什么是R语言的环境，非常简单易懂。
 
 - [Environments in R](https://digitheadslabnotebook.blogspot.com/2011/06/environments-in-r.html) (190128; 190408)  
 介绍了R中的环境和一些相关的内容，对于closure和namespace等概念还是无法理解。
 
 - [stringsAsFactors: An unauthorized biography](https://simplystatistics.org/2015/07/24/stringsasfactors-an-unauthorized-biography/) (181110; 190408)  
 据说`stringsAsFactors`参数问题，是R语言历史上争论最激烈的问题。
 
 - [Why do we use arrow as an assignment operator?](https://colinfay.me/r-assignment/) (181110; 190409)  
 介绍了R中使用`<-`作赋值符的由来？
 
 - [Here's why 2019 is a great year to start with R: A story of 10 year old R code then and now](https://jozefhajnala.gitlab.io/r/r908-10-year-old-code/) (190114; 190410)  
 回顾了近十年R的发展历程。

# Data Acquisition

 - [Web Scraping in R: rvest Tutorial](https://www.datacamp.com/community/tutorials/r-web-scraping-rvest?utm_campaign=News&utm_medium=Community&utm_source=DataCamp.com) (190103)  
 爬虫的入门教程，介绍了`rvest`包，只能爬静态网页。
 
 - [How to Scrape Data from a JavaScript Website with R](https://velaco.github.io/how-to-scrape-data-from-javascript-websites-with-R/) (190103)  
 介绍了一种爬取动态网页（？）的方法，要用到`rvest`和`PhantomJS`包，我最终没有使用这种方法，因此也没有尝试。
 
 - [Scraping Javascript-rendered web content using R](https://datascienceplus.com/scraping-javascript-rendered-web-content-using-r/) (190103)  
 跟上面那个好像差不多，也没有去试。
 
 - [Web Scraping with R and PhantomJS](https://www.datacamp.com/community/tutorials/scraping-javascript-generated-data-with-r) (190103)  
 还是同上。
 
 - [Basics·RSelenium/](http://ropensci.github.io/RSelenium/articles/basics.html) (190103)  
 `RSelenium`包的官方网站，这个包可以用来爬取动态网页，我试了这种方法，成功了，其实就是用来模拟鼠标操作的。

 - [Data acquisition in R (1/4)](https://ikashnitsky.github.io/2017/data-acquisition-one/);  
 [Data acquisition in R (2/4)](https://ikashnitsky.github.io/2017/data-acquisition-two/);  
 [Data acquisition in R (3/4)](https://ikashnitsky.github.io/2017/data-acquisition-three/) (190114)  
 介绍了一些数据的获取方法，似乎并不会有第四部分了。
 
 - [R Data Import/Export](https://cran.r-project.org/doc/manuals/r-release/R-data.html)(190114)  
 介绍数据导入和导出的文档，内容似乎比较旧，而且很多也用不上，需要的时候可以参考一下。
 

# Machine Learning

 - [Machine Learning Basics](https://www.quantinsti.com/blog/machine-learning-basics?utm_campaign=News&utm_medium=Community&utm_source=DataCamp.com) (190319)  
 介绍了机器学习的历史，与深度学习和人工智能的关系，机器学习的原理和基本概念及对未来发展的展望，图文并茂。

 - [How to Prepare for a Machine Learning Interview](https://semanti.ca/blog/?how-to-prepare-for-a-machine-learning-interview&utm_campaign=News&utm_medium=Community&utm_source=DataCamp.com) (190313)  
 介绍如何应对机器学习的面试，后面列了一堆问题，几乎没有会的，但还是希望将来有一天能用上。
 
 - [Feature Engineering](https://engmrk.com/feature-engineering-ver2/?utm_campaign=News&utm_medium=Community&utm_source=DataCamp.com) (190325)  
 介绍了特征工程中可以采用的四种方法。
 
 - [Essentials of Machine Learning Algorithms (with Python and R Codes)](https://www.analyticsvidhya.com/blog/2017/09/common-machine-learning-algorithms/) (190326)  
 介绍了一些常见的机器学习算法，和使用python和R跑这些模型的思路，以及相关的学习资源。
 
 - [The Curse of Dimensionality in classification](http://www.visiondummy.com/2014/04/curse-dimensionality-affect-classification/) (190326)  
 介绍了变量过多时会产生的过度拟合问题，以及解决办法。虽然用了小猫小狗的图片，但还是没法全看懂。
 
 - [The Most Important Machine Learning Algorithms](https://semanti.ca/blog/?the-most-important-machine-learning-algorithms&utm_campaign=News&utm_medium=Community&utm_source=DataCamp.com) (190520)  
 介绍了一些机器学习算法的优缺点。

 - [Machine Learning in R for beginners](https://www.datacamp.com/community/tutorials/machine-learning-in-r) (190103; 190318)  
 以KNN算法介绍了机器学习的整个流程，简单易懂。最后部分还介绍一下了`caret`包。
 
  - [A visual introduction to machine learning](http://www.r2d3.us/visual-intro-to-machine-learning-part-1/?from=%40&utm_campaign=News&utm_medium=Community&utm_source=DataCamp.com) (190103; 190318);  
  [Model Tuning and
the Bias-Variance Tradeoff](http://www.r2d3.us/visual-intro-to-machine-learning-part-2/?from=%40&utm_campaign=News&utm_medium=Community&utm_source=DataCamp.com) (190103; 190318)  
系列文章，利用决策树算法对机器学习中的一些概念以及bias和variance之间的权衡进行了介绍，网页做得很酷炫，但跟R没有关系。似乎会有第三部分，但目前还没见到。

 - [Introduction to Machine Learning for non-developers](https://blog.datascienceheroes.com/introduction-to-machine-learning-for-non-developers/) (190103; 190318)  
 利用随机森林算法简单介绍了下机器学习，虽然没有用到R，但最后推荐了一下R。
 
  - [A very basic introduction to Random Forests using R](http://www.blopig.com/blog/2017/04/a-very-basic-introduction-to-random-forests-using-r/) (190103; 190318)  
  针对`iris`数据集通过R对随机森林算法进行了介绍。
  
  - [Random Forests in R](https://datascienceplus.com/random-forests-in-r/) (190318)  
  简单介绍了一点随机森林的理论知识，并附了一个R的实例。
  
  - [Kaggle Bike Sharing Demand Prediction – How I got in top 5 percentile of participants?](https://www.analyticsvidhya.com/blog/2015/06/solution-kaggle-competition-bike-sharing-demand/) (190326) 
  介绍了作者在kaggle上参与竞赛的完整流程。
  
  - [Machine Learning for Insurance Claims](https://www.tychobra.com/posts/claims-ml/) (190328)  
  使用逻辑回归和`xgboost`对保险索赔分别进行了分类和预测，不懂背景知识，好像预测得不咋样啊，不过有个相关的`shiny`做的还挺不错的，有时间学习一下。

# Onlinebook

 - [R for Data Science](https://r4ds.had.co.nz/) (181107)  
 这本书应该是目前关于R语言数据分析的最好的一本书了，看过两遍，除了太偏向计算机专业和统计学专业的内容，都还好，虽然不建议从这本入门，但真正想学好R，肯定不能错过这本书。

 - [The tidyverse style guide](https://style.tidyverse.org/) (181107)  
 跟上面的书配套的书，介绍了`tidyverse`的代码风格，是在[Google's R Style Guide](https://google.github.io/styleguide/Rguide.xml)的基础之上逐渐演变出来了，可以使代码看起来更美观，更有可读性。

 - [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) (181107)  
 系统介绍`Rmarkdown`的书，主要是作为参考书，有选择性的阅读某些章节即可（然而我还是完整看了一遍）
 
 - [Handling Strings with R](http://www.gastonsanchez.com/r4strings/) (181108)   
 介绍字符串处理的书，内容不多，也比较简单。

 - [Text Mining with R](https://www.tidytextmining.com/) (181108)  
 介绍了几种文本分析的技术以及几个案例，我个人比较喜欢的一本书，喜欢文本挖掘的可以看看。

 - [blogdown: Creating Websites with R Markdown](https://bookdown.org/yihui/blogdown/) (181108)  
 介绍如何用`blogdown`包搭建博客的书，然而我并没有通过这本书真正学会怎么搭博客，只是了解到了自己的知识有多么匮乏。

 - [An Introduction to Statistical and Data Sciences via R](https://moderndive.com/index.html) (181108)  
 介绍了一些统计和`tidyverse`包的基本知识，非常简单，适合入门，但目前这本书还没有完成。

 - [Data Visualization with R](https://rkabacoff.github.io/datavis/) (181108)  
 介绍了很多种图形的绘制方法，非常实用，如果早看到这本书，很多地方都不用我自己去研究了，强烈推荐。

 - [Data Visualization: A practical introduction](http://socviz.co/) (181108)  
 挺久以前看的了，当时还没有完成，而且以前似乎不是叫现在这个名字。感觉没有上面那本书好，但有一章介绍了一些绘图的理论，值得一看。

 - [R Programming for Data Science](https://bookdown.org/rdpeng/rprogdatascience/) (181112)  
 两年前的书，部分内容已经过时了，但帮我补充了很多诸如**Vectorized Operations**，**Lazy Evaluation**，**Scoping Rules**的知识，另外也让我找到了之前想了很久都没想起来的`dput`函数。
 
 - [Exploratory Data Analysis with R](https://bookdown.org/rdpeng/exdata/) (181130)  
 跟上面那本书是同一个作者，部分内容有重叠，虽然主要以`Base`绘图为主，但也介绍了`ggplot2`的一些内容，值得一看；另外，还有几章介绍了层次聚类、K均值聚类以及降维，基本上是没看懂。
 
 - [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/) (190128)  
 `bookdown`的文档，我应该是用不上，随便看看。
 
 - [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/) (190128)  
 用`bookdown`写的书都会发布在这里，这一模块的大部分书都能在这里找到。
 
 - [R in Action, Second Edition](https://www.manning.com/books/r-in-action-second-edition?a_bid=5c2b1e1d&a_aid=RiA2ed) (190221)  
 《R语言实战》英文第二版的在线版，可以免费看。
 
 - [Mastering Software Development in R](https://bookdown.org/rdpeng/RProgDA/) (190313)  
 介绍如何使用R进行开发的书，前两章主要讲了使用R编程的相关知识，后面两章分别介绍了如何使用R开发包和制图工具。很有启发性的一本书，之前不知道该如何实现的一些内容，现在有点思路了，但书中的内容很多都是点到即止，深入学习需要看更专门的书。
 
 - [Fundamentals of Data Visualization](https://serialmentor.com/dataviz/) (190413)  
 人家手里的Aesthetic，才能称得上是Aesthetic啊！
 
 - [Purrr tutorial](https://jennybc.github.io/purrr-tutorial/index.html) (190418)  
 `purrr`包的教程，主要事实际的例子，所以有些重复的地方。
 

# Program

 - [A Tutorial on Loops in R - Usage and Alternatives](https://www.datacamp.com/community/tutorials/tutorial-on-loops-in-r) (190128)  
 介绍了`R`中的几种循环，包括`for`循环、`while`循环以及`repeat`循环，这也是头一次知道`R`里还有个`repeat`循环。
 
   - [Writing better R functions part one ](https://ibecav.github.io/betterfunctions/) (190221);  
  [Writing better R functions part two](https://ibecav.github.io/betterfunctions2/) (190221)；  
  [Writing better R functions part three](https://ibecav.github.io/betterfunctions3/) (190221)；  
  [Writing better R functions part four](https://ibecav.github.io/betterfunctions4/) (190221)
  通过一个实例，介绍了创建函数和完善函数的完整过程。看到第二部分就有点跟不上了，还是要通过自己的实际操作来掌握这些内容。
 
 - [Adding strings in R](https://jcarroll.com.au/2018/10/06/adding-strings-in-r/) (190303)  
 通过编写一个用于连接字符的`+`函数，引出了很多有意思（而且看不太懂）的话题。


# Tidyverse

 - [Getting Started with the Tidyverse: Tutorial](https://www.datacamp.com/community/tutorials/tidyverse-tutorial-r) (181108)  
 简单介绍了一下`tidyverse`包中的几个主要函数，没啥难度，部分内容需要翻墙才能看到。

 - [Pipes in R Tutorial For Beginners](https://www.datacamp.com/community/tutorials/pipe-r-tutorial#notuse) (181108)  
 介绍了几种常见的管道函数（其实一种就够了），像我一样喜欢把代码都串起来的应该好好学学这个。

 - [Data Wrangling Part 1: Basic to Advanced Ways to Select Columns](https://suzan.rbind.io/2018/01/dplyr-tutorial-1/?utm_campaign=News&utm_medium=Community&utm_source=DataCamp.com)；  
 [Data Wrangling Part 2: Transforming your columns into the right shape](https://suzan.rbind.io/2018/02/dplyr-tutorial-2/)；  
 [Data Wrangling Part 3: Basic and more advanced ways to filter rows](https://suzan.rbind.io/2018/02/dplyr-tutorial-3/)；  
 [Data Wrangling Part 4: Summarizing and slicing your data](https://suzan.rbind.io/2018/04/dplyr-tutorial-4/) (181108)  
 系统介绍`dplyr`包的系列文章，非常值得一看。

 - [TIDYING MESSY EXCEL DATA (TIDYXL)](https://statbandit.wordpress.com/2018/05/08/tidying-messy-excel-data-tidyxl/) (190128)  
 介绍了几种清洗excel数据表格的包。


# Website
 
 - [Statistical tools for high-throughput data analysis](http://www.sthda.com/english/) (181108)  
 看过可视化那部分，介绍`ggplot2`包的内容规范而细致，适合入门。
 
 - [stat545](http://stat545.com/topics.html) (181108)  
 一系列文章的汇总，体系有点乱，但内容还不错，记得正则表达式就是在这里学会的，对我帮助挺大。
 
 - [Cookbook for R ](http://www.cookbook-r.com/) (181208)  
 很早就知道的一个网站，但最近才完整看了一遍，除了`ggplot2`部分，都比较旧了，但有一些自编函数的例子，需要时可以参考一下。
 
 - [Data Analysis and Visualization in R for Ecologists](https://datacarpentry.org/R-ecology-lesson/index.html) (190114)  
 一个简单但实用的R教程网站，跟生态学好像也没啥太多的关系，有一部分数据库的内容还挺适合我的。


# Visualization

### Basic
 
 - [Beautiful plotting in R: A ggplot2 cheatsheet](http://zevross.com/blog/2014/08/04/beautiful-plotting-in-r-a-ggplot2-cheatsheet-3/) (181110)  
 非常不错的一个`ggplot2`基础教程，如果有不知道该如何实现的地方，可以来这篇文章查一查。
 
 - [Under the hood of ggplot2 graphics in R](http://zevross.com/blog/2014/11/20/under-the-hood-of-ggplot2-graphics-in-r/) (181110)  
 上面那篇文章的作者的另一篇文章，没怎能看懂，先放着吧。
 
 - [The Complete ggplot2 Tutorial - Part1 | Introduction To ggplot2](http://r-statistics.co/Complete-Ggplot2-Tutorial-Part1-With-R-Code.html) (190619)  
 介绍了`ggplot2`绘图的一些基本知识，比较有用的地方在于给出了取消科学记数法的方法以及对比了两种不同的坐标值数值limit。
 
 - [The Complete ggplot2 Tutorial - Part 2 | How To Customize ggplot2](http://r-statistics.co/Complete-Ggplot2-Tutorial-Part2-Customizing-Theme-With-R-Code.html) (190619)  
 上面那篇文章的第二部分，较为系统的介绍了如何定制`ggplot2`统计图。
 
### Collection

 - [the R Graph Gallery](https://www.r-graph-gallery.com/) (181114)  
 汇总了很多可以用基础绘图工具和`ggplot2`绘制的图，附有相应的代码，可以说是非常棒的一个网站了。
 
  - [How to Pick the Perfect Color Combination for Your Data Visualization] (https://blog.hubspot.com/marketing/color-combination-data-visualization) (190629)  
  介绍了几个给统计图配色的网站。
 
### Common Plots

  - [Pretty histograms with ggplot2](https://drsimonj.svbtle.com/pretty-histograms-with-ggplot2) (181113; 190306)  
 使用`ggplot2`绘制直方图的一个简单例子，同时介绍了针对连续性变量的颜色使用方法。

 - [Pretty scatter plots with ggplot2](https://drsimonj.svbtle.com/pretty-scatter-plots-with-ggplot2) (181113; 190516)  
 介绍了散点图的绘制方法，值得学习的地方是提供了一种透明图的映射方法。

 - [Exploring ggplot2 boxplots - Defining limits and adjusting style](https://owi.usgs.gov/blog/boxplots/) (190306)  
 非常详尽的箱线图绘制教程，不仅介绍了如何使用`ggplot2`绘制箱线图，还提供了很多针对图形进行调整的技术细节，值得仔细钻研一番。
 
  - [Bump Chart](https://dominikkoch.github.io/Bump-Chart/) (181110; 190516)  
 介绍了一种叫**Bump Chart**的折线图画法，顺便提到了如何把国旗映射到图中。
 
  - [Label line ends in time series with ggplot2](https://drsimonj.svbtle.com/label-line-ends-in-time-series-with-ggplot2) (181110; 190516)  
 利用`sec.axis`参数给折线图的终点处贴标签，这个方法应该还有其他的用处。
 
### Extension

 - [ggplot2 extensions](http://www.ggplot2-exts.org/) (181113)  
 介绍了基于`ggplot2`的一些扩展包。
 
 - [htmlwidgets for R](http://gallery.htmlwidgets.org/) (181113)  
 R的一些可视化方面（也不全是）的扩展包。

 - [googleVis examples](https://cran.r-project.org/web/packages/googleVis/vignettes/googleVis_examples.html) (181114)  
 `gppgleVis`包的例子介绍，这些图都很漂亮，有时间一定要研究一下这个包。

 - [setting ggplot2 background with ggbackground](https://guangchuangyu.github.io/2018/04/setting-ggplot2-background-with-ggbackground/) (181110)  
 给`ggplot2`作的图加个背景。
 
 - [PUTTING THE CAT IN SCATTERPLOT](https://www.mango-solutions.com/blog/putting-the-cat-in-scatterplot) (181113)  
 把猫的图片放进了散点图里，挺有意思。

 - [I made a 3D movie with ggplot2 once - here's how I did it](https://www.data-imaginist.com/2017/i-made-a-3d-movie/) (181113)  
 没有标题说的那么夸张，只是做了个3D动图（然而也很厉害了）。
 
 - [Tao of Tidygraph](http://www.questionflow.org/2018/03/06/tao-of-tidygraph/) (181114)  
 使用`tidygraph`包对一本名为**Tao Te Programming**的书进行了**network analysis**，可惜这本书并不能免费获得。
 
 - [Infographic-style charts using the R waffle package] (https://nsaunders.wordpress.com/2017/09/08/infographic-style-charts-using-the-r-waffle-package/) (190629)  
 用`waffle`包绘制信息图。
 
### Map

 - [Bitcoin (World Map) Bubbles](https://rud.is/b/2018/01/18/bitcoin-world-map-bubbles/) (181114; 190509)  
 一张关于比特币网络的非常漂亮的地图。
 
 - [Three ways of visualizing a graph on a map](https://datascience.blog.wzb.eu/2018/05/31/three-ways-of-visualizing-a-graph-on-a-map/) (190509)  
 介绍了几种在R中绘制地图的方法，主要是利用`ggraph`解决了分别设定曲线和点的大小的问题。
 
 - [Drawing beautiful maps programmatically with R, sf and ggplot2 — Part 1: Basics](https://www.r-spatial.org//r/2018/10/25/ggplot2-sf.html#fnref:1) (190714)  
 [Drawing beautiful maps programmatically with R, sf and ggplot2 — Part 2: Layers](https://www.r-spatial.org//r/2018/10/25/ggplot2-sf-2.html) (190714)  
 [Drawing beautiful maps programmatically with R, sf and ggplot2 — Part 3: Layouts](https://www.r-spatial.org//r/2018/10/25/ggplot2-sf-3.html) (190714)  
 系列文章，介绍了如何使用`ggplot2`和`sf`包绘制地图。

### Modification

  - [Ordering categories within ggplot2 facets](https://drsimonj.svbtle.com/ordering-categories-within-ggplot2-facets) (181110; 190516)  
  解决了分面后的柱形图的排序问题。
  
  - [Customizing time and date scales in ggplot2](https://www.statworx.com/de/blog/customizing-time-and-date-scales-in-ggplot2/) (181110; 190516)  
  较详细地讲解了坐标轴上时间标度的设置，也可以迁移到其他类型的标度。
  
  - [How to combine point and boxplots in timeline charts with ggplot2 facets](https://shirinsplayground.netlify.com/2017/11/combine_point_boxplot_ggplot/) (181113; 190306)  
  利用分面把折线图+散点图与箱型图同时呈现在一起。

 - [You Need to Start Branding Your Graphs. Here's How, with ggplot!](https://michaeltoth.me/you-need-to-start-branding-your-graphs-heres-how-with-ggplot.html) (190516)  
 介绍了如何在数据分析图中添加图片，如公司logo。
 
 - [Coordinate systems in ggplot2: easily overlooked and rather underrated](https://www.statworx.com/blog/coordinate-systems-in-ggplot2-easily-overlooked-and-rather-underrated/) (190516)  
 介绍了`ggplot2`中的坐标系统，最后有折线图转换成雷达图的方法。
 
 - [Adding different annotation to each facet in ggplot](https://buzzrbeeline.blog/2018/11/06/adding-different-annotation-to-each-facet-in-ggplot/) (190714)  
 给分面后的图加注释。

### Theory

 - [10 tips for making your R graphics look their best](https://blog.revolutionanalytics.com/2009/01/10-tips-for-making-your-r-graphics-look-their-best.html) (181113; 190511)  
 很老的文章了，但有几条tips还是很有用的。
 
 - [Visualizations That Really Work](https://hbr.org/2016/06/visualizations-that-really-work) (190511)  
 介绍了可视化的四种类型，并举了相应的例子。非常棒的文章，等水平提高后再看一下，应该会收获更多。
 
